apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feed-system

resources:
- namespace.yaml
- configmap.yaml
- postgres.yaml
- redis.yaml
- kafka.yaml
- feed-api.yaml
- feed-worker.yaml
- hpa.yaml
- monitoring.yaml

commonLabels:
  app.kubernetes.io/name: feed-system
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

images:
- name: feed-system/api
  newTag: latest
- name: feed-system/worker
  newTag: latest

configMapGenerator:
- name: feed-config
  files:
  - configs/config.yaml